sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
env:
  global:
    - buildnum=$TRAVIS_BUILD_NUMBER
install:
  - pip install pre-commit
stages:
  - name: validate
  - name: test
  - name: package
jobs:
  include:
    - stage: validate
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: test
      script:
        - make install
        - make test
    - stage: package
      script:
        - make install
        - make package
